### ISSUE TITLE
Searching an URL hangs

### ISSUE THREAD

**Issue by lucs** [lizmat/App-Rak#40] opened 2023-06-12 12:44 UTC
For me, this hangs:

    rak §reading https://dev.to/lizmat/its-time-to-rak-part-1-30ji

But obtaining the file with 'curl' succeeds:

    curl https://dev.to/lizmat/its-time-to-rak-part-1-30ji

**Comment by lizmat** [comment] 2024-05-09 11:13
I cannot reproduce this:
```
$ rak §reading https://dev.to/lizmat/its-time-to-rak-part-1-30ji 
https://dev.to/lizmat/its-time-to-rak-part-1-30ji
390:aria-label="Add to reading list"
783:<p>Thank you for reading all the way to the end!</p>
```
So assume it is either fixed, or was a temporary fluke?

Closing, please re-open if you disagree.

**Closed by lizmat** 2024-05-09 11:13 UTC
